### ISSUE TITLE
Step 1 of instructions unnecessary

### ISSUE THREAD

**Issue by jvook** [LRFLEW/AM64DS_DeSmuME#1]
"Download the Latest Releases
This is to make sure you have any support files needed for the emulator. You can download the latest release build from https://desmume.org/download/ under "Stable Releases"."

This step is unnecessary.  The Stable releases only includes the EXE and some filler files that do nothing.  Not to mention it's super outdated. AM64DS works fine without this step.

**Comment by LRFLEW** [comment]
I thought the step *might* be unnecessary, but wasn't sure. The reason I included that step was because of wording on the DeSmuME download page (emphasis mine):

> Windows users should **patch the most recent stable release** with an autobuild from here. Just go to the URL which is the latest build and download the executable.

I think keeping it might still make sense if the original emulator's authors have a reason for this, but I can mark it as optional when I update the directions.

**Comment by LRFLEW** [comment]
Marked as "optional" now with the README update. I'm going to consider this issue resolved. If you can think of a reason to leave this issue open, leave a comment and I can re-open it. Thank you for your feedback.
