### ISSUE TITLE
Request:  Add support for 16:9 and other aspects

### ISSUE THREAD

**Issue by jvook** [LRFLEW/AM64DS_DeSmuME#2]
There are 16:9 aspect cheats available on the internet.  However getting Desmume to display in 16:9 is difficult.  The only option relating to AR is whether or not to maintain the DS aspect.  However, it's only possible to stretch the image to 16:9 if you disable the second screen.  I think it would be ideal if your emulator supported playing SM64 in 16:9 as I believe your emulator will be the definitive way to play SM64.  There is already a fork of Desmume that supports different AR called DesmumAR https://github.com/rlaPHOENiX/DeSmuMAR

I have already put a lot of thought into this so I will tell you what I think would be really cool and see what you think.  First get the game running in 16:9, full screen.  Then draw the second screen on top of the top screen so that it works like a minimap.  Also I think it is thoeretically possible to draw the second screen with a transparent background.  It should be possible to have an AR code that draws a unique background color on the second screen, and then it can be drawn transparent, like a green screen.  This would give a nice minimap effect and still have full screen.  It would also be good to have an AR code to prevent drawing mario's lives/stars and the camera rotation arrows on the second screen.

**Comment by LRFLEW** [comment]
This is a *little* outside of the scope of what I'm trying to do here.

For DesmumAR, looking at the project, it seems to be acting as a wrapper around DeSmuME, so I don't see any reason why it would be incompatible with this modified DeSmuME (since it doesn't appear to require a specific build of DeSmuME). I have no plans to incorporate it natively, however.

As to the idea of overlaying the two screens... that is **way** beyond what I want this project to be. I have no plans on implementing anything like that, but I'd say you, or anybody else, is free to implement something like that on top of what I've done here.

**Comment by LRFLEW** [comment]
I'm going to close this issue as being out-of-scope for this project. If you think this is a feature that upstream (i.e. the original version) should consider, I'd recommend opening an issue there. I'm going to close this issue, as I don't see this as something I'm going to work on. Thank you for your feedback.
