### ISSUE TITLE
Request: Add right analog support

### ISSUE THREAD

**Issue by jvook** [LRFLEW/AM64DS_DeSmuME#3]
Requesting that you can use right analog for camera control (needn't be analog control)
Pressing L should center camera
I don't know if this is possible but what about an AR code to prevent drawing red arrows during camera rotation?
And an AR code to silence camera rotation noise? (it should still make error noise when camera can't rotate)

**Comment by LRFLEW** [comment]
Ok, there's actually a few requests tied together here, so I'm going to break this up a bit.

> Requesting that you can use right analog for camera control (needn't be analog control)

I've actually been thinking about this after watching a Twitch streamer mention that they were using AutoHotkey to achieve this. Currently this *is* possible to some extent. Switching your controls to "Touch Mode" (in the pause menu) puts camera rotation on X and Y, and you can map the analog stick to these buttons in the "Control Config" menu in DeSmuME.

However, I'll grant you that this isn't an optimal solution. You can't get **both** camera rotation and camera distance on buttons at the same time. However, I'd like to avoid changing the emulator too much for this, as I am trying to get this merged into the official project (TASVideos/desmume#435). So how about a compromise: While working on the Wii U solution, I figured out how the button mappings for the three different controls work, so I can edit the button controls as I want. Since the D-Pad is unused with this mod, I can bind the camera controls to the D-Pad, and then if people want it on the right analog stick, they can use the "Control Config" to bind the D-Pad to the analog stick.

> Pressing L should center camera

Isn't this already the case?

> I don't know if this is possible but what about an AR code to prevent drawing red arrows during camera rotation?
And an AR code to silence camera rotation noise? (it should still make error noise when camera can't rotate)

I'd consider these cosmetic changes, and unrelated to this project in particular. If I have time, I can look into this, but I probably won't incorporate these changes into this project (i,e, make them a separate project)

The closest I would consider prioritizing is getting rid of the camera control buttons on the lower screen if I put the controls on the D-Pad, but I would need to look into how to do that, so no promises.

**Comment by LRFLEW** [comment]
Ok, so I spent some time and figured out the changes needed to put the camera rotation on the D-Pad. This only affects "Standard Mode", but here's a code for the North American revision 1:

```
E2074044 00000008
02000100 00000000
02024760 EA00000C
520F4054 E59F12B0
020F4054 EA000071
D2000000 00000000
```

I can work on porting it to the other revisions, but there's something I'm considering doing. Right now the camera controls are "inverted". I.E. when you press left, the camera shows what's to the right, and vice versa. This is how the original game handled the camera. I'm thinking about adding at least the option of un-inverting the camera. This *can* be done in the emulator by just swapping the left and right directions, but the arrows that appear in-game won't be right, and the Wii U port of this I'm making won't have that luxury.

I'd like to know people's thoughts on doing this, though. It will probably be significant effort, especially if I want to update the game's graphics in the controls selection to account for it.

**Comment by jvook** [comment]
Yeah like I said just throwing some things out there because I've had the idea of a purpose-built SM64DS emulator before.  I'd rather get the ideas in early in case your scope was bigger or ever changes :)

As you said the d-pad is unnecessary so you can just put it on the right analog, which is the main thing.

**Comment by LRFLEW** [comment]
The project has been updated with codes and patch files that include controlling the camera with the D-Pad. Since you can rebind the D-Pad to an analog stick, I'm going to consider this issue resolved. If you can think of a reason to leave this issue open, leave a comment and I can re-open it. Thank you for your feedback.
